# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmMYZN_--5E18IiZgPGjoVY4hKKzJBjV
"""

import streamlit as st
import pandas as pd
import qrcode
from PIL import Image, ImageDraw, ImageFont
import io
import os

# Load all sheets from the uploaded Excel file
def load_all_sheets(file):
    return pd.read_excel(file, sheet_name=None, dtype=str)

# Search for product code across multiple sheets
def find_product(data_sheets, product_code):
    for sheet_name, df in data_sheets.items():
        if "DESIGN NO" in df.columns and product_code in df["DESIGN NO"].values:
            return df[df["DESIGN NO"] == product_code].iloc[0].to_dict()
    return None

# Generate QR Code
def generate_qr(data):
    qr = qrcode.QRCode(version=1, box_size=10, border=4)
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill="black", back_color="white")
    return img

# Create Label Image with QR Code
def create_label(product_data, party_code, order_no):
    label_width, label_height = 400, 300
    img = Image.new("RGB", (label_width, label_height), "white")
    draw = ImageDraw.Draw(img)

    # Load Font
    try:
        font = ImageFont.truetype("arial.ttf", 16)
    except:
        font = ImageFont.load_default()

    # Add Text
    text = f"Order No: {order_no}\nParty Code: {party_code}\n"
    fields_to_include = ["MACH CODE", "WIDTH", "THICK", "MACH NAME", "DULL/NO DULL"]

    for key in fields_to_include:
        if key in product_data:
            text += f"{key}: {product_data[key]}\n"

    draw.text((10, 10), text, fill="black", font=font)

    # Generate QR Code
    qr_data = f"Order No: {order_no}, Party Code: {party_code}, " + ", ".join(f"{k}: {v}" for k, v in product_data.items())
    qr_img = generate_qr(qr_data)
    qr_img = qr_img.resize((100, 100))

    # Paste QR Code on Label
    img.paste(qr_img, (280, 180))

    return img

# Streamlit App
st.title("QR Code Label Generator")

uploaded_file = st.file_uploader("Upload Excel File", type=["xlsx"])

if uploaded_file:
    data_sheets = load_all_sheets(uploaded_file)

    product_code = st.text_input("Enter Product Code:")

    if st.button("Fetch Product Data"):
        product_data = find_product(data_sheets, product_code)

        if product_data:
            party_code = st.text_input("Party Code", "")
            order_no = st.text_input("Order No", "")

            # Editable Fields
            for key in ["MACH CODE", "WIDTH", "THICK", "MACH NAME", "DULL/NO DULL"]:
                if key in product_data:
                    product_data[key] = st.text_input(key, product_data[key])

            if st.button("Generate Label"):
                label_img = create_label(product_data, party_code, order_no)

                # Convert image to bytes
                img_byte_arr = io.BytesIO()
                label_img.save(img_byte_arr, format="PNG")
                img_byte_arr.seek(0)

                # Display Label Preview
                st.image(label_img, caption="Generated Label", use_column_width=False)

                # Download Option
                st.download_button("Download Label", img_byte_arr, file_name="label.png", mime="image/png")

                # Print Duplicate Option
                if st.button("Print Duplicate Label"):
                    label_img.save("label_print.png")
                    os.system(f"start label_print.png")  # Windows
                    st.success("Duplicate Label Sent to Printer!")
        else:
            st.error("Product Code not found in any sheet.")

